kn = linspace(0,10,1000);
c = 1.11;
fc = (1 + 4*c*kn);
loglog(kn,fc,...
    'LineWidth',1.3,...
    'color','r');

% axis([-0.1 1.1 0 (max(v_dsmc) + 0.1)]);

fontSize = 24;
hax = gca;
set(hax, 'fontsize',fontSize ...
    );

set(get(hax,'xlabel'), ...
    'String', 'Knudsen number', ...
    'fontsize',fontSize ...
    );

set(get(hax,'ylabel'), ...
    'String', 'Klinkenberg correction factor', ...
    'fontsize',fontSize ...
    );

set(get(hax,'title'), ...
    'String', 'Klinkenberg correction factor', ...
    'fontsize',fontSize ...
    );