function one_cylinder_varying_knudsen()
base_folder = '/projects/data/dsmc/2013-12-10_one_cylinder/one_cylinder_liquid_permeability/states/';
knudsen_numbers = linspace(1,100,100)*0.1;
permeabilities = [];
radius = 0.45;

for i=1:length(knudsen_numbers)
	state_folder = sprintf('%s/%6f/01_sampling/',base_folder, knudsen_numbers(i));
	filename_permeability = sprintf('%s/statistics/permeability.txt',state_folder);
    
    area = pi*radius^2;
	permeability = dlmread(filename_permeability) / area;
    permeabilities = [permeabilities permeability];
end

radius_cm = radius*1e-4;
absolute_permeability = radius_cm^2/8;
analytical_permeabilities = knudsen_correction_factor(knudsen_numbers)*absolute_permeability;
analytical_permeabilities_klinkenberg = klinkenberg_correction_factor(knudsen_numbers)*absolute_permeability;

plot(knudsen_numbers, permeabilities,...
    'LineWidth',1.5,...
    'LineStyle','o',...
    'color','r'...
    );
hold on
plot(knudsen_numbers, analytical_permeabilities,...
    'LineWidth',1.5...
    );
plot(knudsen_numbers, analytical_permeabilities_klinkenberg,...
    'LineWidth',1.5,...
    'color','k'...
    );

fontsize = 20;
hax = gca;

set(hax, 'fontsize',fontsize ...
    );
xlabel('Knudsen number',...
    'fontsize',fontsize...
    );
ylabel('Permeability [cm^2]',...
    'fontsize',fontsize ...
    );
title('Cylinder permeability',...
    'fontsize',fontsize ...
    );
legend({'DSMC','Knudsen corrected', 'Klinkenberg corrected'},...
    'fontsize',fontsize...
    );
end