cpus = 2.^linspace(0,9,10);

t = [ ];
eta_s = t(1)./(cpus.*t)

plot(cpus,eta_s);

fontsize = 20;
hax = gca;
set(hax, 'fontsize',fontsize ...
    );
xlabel('Number of processors',...
    'fontsize',fontsize...
    );
ylabel('\eta_s',...
    'fontsize',fontsize ...
    );
title('Strong scaling efficiency',...
    'fontsize',fontsize ...
    );