cpus = 2.^linspace(0,9,10);

t = [345, 364, 519, 470, 662, 547, 536, 576, 543, 545];
eta_w = t(1)./t

plot(cpus,eta_w);

fontsize = 20;
hax = gca;
set(hax, 'fontsize',fontsize ...
    );
xlabel('Number of processors',...
    'fontsize',fontsize...
    );
ylabel('\eta_w',...
    'fontsize',fontsize ...
    );
title('Weak scaling efficiency',...
    'fontsize',fontsize ...
    );